version: "3.8"

services:
  app-1:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    ports:
      - "8081:8080"
  app-2:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    ports:
      - "8082:8080"
  app-3:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    ports:
      - "8083:8080"

  rr:
    build:
      context: .
      dockerfile: ./docker/rr.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - app-1
      - app-2
      - app-3